#!/bin/bash
#
### BEGIN INIT INFO
# Provides: $storm-supervisor
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

# Source function library.
. /etc/init.d/functions
RETVAL=0

STORM_USER=storm
PID_FILE="/var/run/storm/storm-supervisor.pid"

STORM_HOME="/opt/storm"
LIB="$STORM_HOME/lib"
STORM_JAR=($STORM_HOME/storm-*.jar)
STORM_CONF="$STORM_HOME/conf"
STORM_LOG="$STORM_HOME/log4j"

CLASSPATH="$LIB/*:$STORM_JAR:$STORM_CONF:$STORM_LOG"

JVM_TYPE="server"
SUPERVISOR_JVM_MEMORY="1024m"
SUPERVISOR_JVM_OPTS=""

# Source config
. /etc/sysconfig/storm

start() {
    if storm_status>/dev/null; then
    	echo "Storm supervisor is already running."
    	exit 1
    else
    	echo "Starting storm supervisor..."
    fi 
    STORM_CMD="java -$JVM_TYPE -Xmx$SUPERVISOR_JVM_MEMORY -Djava.library.path=\"$JAVA_LIBRARY_PATH\" -Dstorm.options=\"$STORM_OPTIONS\" -Dstorm.home=\"$STORM_HOME\" -Dlogfile.name=supervisor.log $SUPERVISOR_JVM_OPTS -cp \"$CLASSPATH\" backtype.storm.daemon.supervisor &"
    runuser --shell=/bin/bash --preserve-environment $STORM_USER --command="$STORM_CMD > /dev/null && echo \$! > $PID_FILE"
    RETVAL=$?
    storm_status
    return $RETVAL
}

stop() {
    if storm_status; then
        echo "Stopping storm supervisor..."
        killproc -p $PID_FILE -TERM
        RETVAL=$?
        storm_status
    else
        return 0
    fi
    return $RETVAL
}

storm_status() {
    status -p $PID_FILE storm-supervisor
    return $?
}

restart() {
        stop
        start
}

reload()  {
    restart
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        storm_status
        ;;
  restart)
        restart
        ;;
  reload)
        reload
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac

exit $?
