#!/bin/bash
#
### BEGIN INIT INFO
# Provides: $storm-logviewer
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

# Source function library.
. /etc/init.d/functions
RETVAL=0

STORM_USER=storm
PID_FILE="/var/run/storm/storm-logviewer.pid"

# Source config
. /etc/sysconfig/storm

CLASSPATH="$STORM_LIB/*:$STORM_CONF"

# Source config
. /etc/sysconfig/storm

start() {
    if storm_status>/dev/null; then
    	echo "Storm logviewer is already running."
    	exit 1
    else
    	echo "Starting storm logviewer..."
    fi 
    STORM_CMD="java -$JVM_TYPE -Xmx$LOGVIEWER_JVM_MEMORY -Duser.dir=\"$STORM_HOME\" -Djava.library.path=\"$JAVA_LIBRARY_PATH\" -Dstorm.options=\"$STORM_OPTIONS\" -Dstorm.home=\"$STORM_HOME\" -Dstorm.log.dir=\"$STORM_LOG_DIR\" -Dlogfile.name=logviewer.log $LOGVIEWER_JVM_OPTS -cp \"$CLASSPATH\" backtype.storm.daemon.logviewer &"
    runuser --shell=/bin/bash --preserve-environment $STORM_USER --command="$STORM_CMD > /dev/null && echo \$! > $PID_FILE"
    RETVAL=$?
    storm_status
    return $RETVAL
}

stop() {
    if storm_status; then
        echo "Stopping storm logviewer..."
        killproc -p $PID_FILE -TERM
        RETVAL=$?
        storm_status
    else
        return 0
    fi
    return $RETVAL
}

storm_status() {
    status -p $PID_FILE storm-logviewer
    return $?
}

restart() {
        stop
        start
}

reload()  {
    restart
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        storm_status
        ;;
  restart)
        restart
        ;;
  reload)
        reload
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac

exit $?

